INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE, CATEGORY, PRODUCTION_YEAR ) VALUES (1, 'TIT1', 'DESC1', 10.0, 'COMEDY', '1990');
INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE , CATEGORY, PRODUCTION_YEAR ) VALUES (2, 'TIT2', 'DESC2', 20.5, 'DRAMA', '2010');
INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE , CATEGORY, PRODUCTION_YEAR ) VALUES (3, 'TIT3', 'DESC3', 30.25, 'CAT2', '2020');
INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE , CATEGORY, PRODUCTION_YEAR ) VALUES (4, 'TIT4', 'DESC4', 5.345, 'MATRIOAL ARTS', '2003');
INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE , CATEGORY, PRODUCTION_YEAR ) VALUES (5, 'TIT5', 'DESC5', 10.40, 'COMEDY', '2000');
