INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE, DIRECTOR ) VALUES (1, 'TIT1', 'DESC1', 10.0, 'DIRECTOR NUM1');
INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE , DIRECTOR ) VALUES (2, 'TIT2', 'DESC2', 20.5, 'DIRECTOR SOMEBODY');
INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE , DIRECTOR ) VALUES (3, 'TIT3', 'DESC3', 30.25, 'DIR JR. SMITH');
INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE , DIRECTOR ) VALUES (4, 'TIT4', 'DESC4', 5.345, 'DIRECTOR 4');
INSERT INTO "MOVIE" (ID, TITLE , DESCRIPTION , PRIZE , DIRECTOR ) VALUES (5, 'TIT5', 'DESC5', 10.40, 'DIRECTOR 5');
